#!/bin/sh

if [ -z "$1" ]
then
    echo "Usage: `basename $0` PACKAGE-NAME [PARAMETERS]"
    exit 1
fi

PACKAGE=$1
shift

ccl -Q -b \
    --eval "(faslpath:load-package '#:$PACKAGE)" \
    --eval "($PACKAGE::main)" \
    --eval "(quit)" "$@"

