#!/bin/sh

if [ -z "$1" ]
then 
    echo "Usage: `basename $0` PACKAGE-NAME"
    exit 1
fi

clisp -q \
      -on-error abort \
      -x "(faslpath:compile-package '#:$1)" \
      -x "(faslpath:load-package :faslpath.extras)" \
      -x "(faslpath.extras:make-package-lisp-core \"$1\")"
