#!/bin/sh

if [ -z "$1" ]
then
    echo "Usage: `basename $0` PACKAGE-NAME"
    exit 1
fi

sbcl --noinform \
     --disable-debugger \
     --eval "(faslpath:compile-package '#:$1)" \
     --eval "(quit)"
